export const EVOLUTION_LEVELS = [
  { level: 1, name: 'Sơ sinh', radius: 14, color: '#FFEBEE', points: 2, emoji: '👶', lore: 'Mầm non mới nhú, khởi đầu của mọi vĩ nghiệp.' },
  { level: 2, name: 'Mầm non', radius: 18, color: '#FCE4EC', points: 4, emoji: '🧸', lore: 'Thế giới là một sân chơi đầy màu sắc.' },
  { level: 3, name: 'Tiểu học', radius: 22, color: '#F3E5F5', points: 8, emoji: '🎒', lore: 'Nét chữ đầu đời, sách bút là bạn thân.' },
  { level: 4, name: 'Trung học', radius: 27, color: '#EDE7F6', points: 16, emoji: '🛹', lore: 'Tuổi nổi loạn với những giấc mơ bay bổng.' },
  { level: 5, name: 'Thanh niên', radius: 33, color: '#E8EAF6', points: 32, emoji: '🎸', lore: 'Nhiệt huyết dâng trào, khát vọng khẳng định mình.' },
  { level: 6, name: 'Đại học', radius: 40, color: '#E3F2FD', points: 64, emoji: '🎓', lore: 'Kiến thức là chìa khóa mở cánh cửa tương lai.' },
  { level: 7, name: 'Việc làm', radius: 48, color: '#E1F5FE', points: 128, emoji: '💼', lore: 'Gánh vác trách nhiệm, xây dựng nền tảng vững chắc.' },
  { level: 8, name: 'Tình yêu', radius: 57, color: '#E0F7FA', points: 256, emoji: '💖', lore: 'Hai tâm hồn tìm thấy nhau giữa biển người.' },
  { level: 9, name: 'Kết hôn', radius: 67, color: '#E0F2F1', points: 512, emoji: '💍', lore: 'Lời thề nguyện trọn đời dưới bóng hoàng hôn.' },
  { level: 10, name: 'Tổ ấm', radius: 79, color: '#E8F5E9', points: 1024, emoji: '🏠', lore: 'Nơi bão dừng sau cánh cửa, tràn ngập tiếng cười.' },
  { level: 11, name: 'Cha mẹ', radius: 93, color: '#F1F8E9', points: 2048, emoji: '👨‍👩‍👧', lore: 'Tình thương vô điều kiện truyền lại đời sau.' },
  { level: 12, name: 'Ông bà', radius: 109, color: '#F9FBE7', points: 4096, emoji: '👴', lore: 'Kể lại chuyện xưa bên tách trà thơm ngát.' },
  { level: 13, name: 'Du lịch', radius: 127, color: '#FFFDE7', points: 8192, emoji: '✈️', lore: 'Khám phá thế giới khi tâm hồn đã an yên.' },
  { level: 14, name: 'Sum vầy', radius: 148, color: '#FFF8E1', points: 16384, emoji: '🍲', lore: 'Bữa cơm tất niên ấm áp tình thân tộc.' },
  { level: 15, name: 'Vĩnh cửu', radius: 172, color: '#FFF3E0', points: 32768, emoji: '🌈', lore: 'Hòa mình vào vũ trụ, để lại danh tiếng muôn đời.' },
];
