export const EVOLUTION_LEVELS = [
  { level: 1, name: 'Sơ sinh', radius: 5, color: '#FFEBEE', points: 2, emoji: '👶' },
  { level: 2, name: 'Mầm non', radius: 6, color: '#FCE4EC', points: 4, emoji: '🧸' },
  { level: 3, name: 'Tiểu học', radius: 8, color: '#F3E5F5', points: 8, emoji: '🎒' },
  { level: 4, name: 'Trung học', radius: 10, color: '#EDE7F6', points: 16, emoji: '🛹' },
  { level: 5, name: 'Thanh niên', radius: 12, color: '#E8EAF6', points: 32, emoji: '🎸' },
  { level: 6, name: 'Đại học', radius: 14, color: '#E3F2FD', points: 64, emoji: '🎓' },
  { level: 7, name: 'Việc làm', radius: 17, color: '#E1F5FE', points: 128, emoji: '💼' },
  { level: 8, name: 'Tình yêu', radius: 21, color: '#E0F7FA', points: 256, emoji: '💖' },
  { level: 9, name: 'Kết hôn', radius: 25, color: '#E0F2F1', points: 512, emoji: '💍' },
  { level: 10, name: 'Tổ ấm', radius: 31, color: '#E8F5E9', points: 1024, emoji: '🏠' },
  { level: 11, name: 'Cha mẹ', radius: 37, color: '#F1F8E9', points: 2048, emoji: '👨‍👩‍👧' },
  { level: 12, name: 'Ông bà', radius: 44, color: '#F9FBE7', points: 4096, emoji: '👴' },
  { level: 13, name: 'Du lịch', radius: 53, color: '#FFFDE7', points: 8192, emoji: '✈️' },
  { level: 14, name: 'Sum vầy', radius: 64, color: '#FFF8E1', points: 16384, emoji: '🍲' },
  { level: 15, name: 'Vĩnh cửu', radius: 77, color: '#FFF3E0', points: 32768, emoji: '🌈' },
];
